[build]
command = "npm run build"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200
