[build]
command = "npm run build"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[edge_functions]
directory = "netlify/edge-functions"

[[edge_functions]]
function = "openai-stream"
path = "/openai-stream"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200
