[build]
command = "npm run build"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[edge_functions]
directory = "netlify/edge-functions"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[edge_functions]]
path = "/.netlify/edge-functions/openai-stream"
function = "openai-stream"
